New Script

diff --git a/appliance/appliance b/appliance/appliance
--- a/appliance/appliance
+++ b/appliance/appliance
@@ -1,72 +1,128 @@
 #!/bin/bash
 # Function to start docker service, check its status, and execute docker compose with given profile
+COMPOSE_FILE="/home/hpe/docker-sap-hana-deploy/ansible/compose.yml" 
 
 start_docker_compose() {
-    echo "Starting Docker service..."
-    sudo systemctl start docker
+    profile=$1
 
-    echo "Starting nfs service..."
-    sudo systemctl start nfs-kernel-server
+    if [ "$profile" = "redhat" ] || [ "$profile" = "suse" ]; then
+      ensure_service_running "docker"
+      ensure_service_running "nfs-kernel-server"
 
-    if [ $(sudo systemctl is-active docker) = "active" ] && [ $(sudo systemctl is-active nfs-kernel-server) = "active" ]; then
-       if [ "$1" = "redhat" ] || [ "$1" = "suse" ]; then
-           echo "Docker & nfs-kernel-server services are running..."
-	   echo ""
-           echo "Executing 'docker compose --file /home/hpe/docker-sap-hana-deploy/ansible/compose.yml --profile $1 up -d'..."
-           docker compose --file /home/hpe/docker-sap-hana-deploy/ansible/compose.yml --profile $1 up -d
-           echo "Docker Compose $1 services have been started."
-           echo ""
-           show_docker_compose_status
-	   echo ""
-       else
-           echo "Invalid argument. Usage: appliance start [redhat|suse]"
-       fi
-    else 
-        if [ $(sudo systemctl is-active docker) = "inactive" ]; then
-	  echo ""
-          echo "Docker service is not running. Please check the service status."
-	fi
-	if [ $(sudo systemctl is-active nfs-kernel-server) = "inactive" ]; then
-          echo ""
-          echo "nfs-kernel-server service is not running. Please check the service status."
-        fi
+      echo "Docker & nfs-kernel-server services are running..."
+      #Check Docker Compose Service
+      container_ids=$(docker compose --file "$COMPOSE_FILE" ps --services "$profile-ansible" -q )
+      if [ ! "$container_ids" ]; then
+	 echo ""
+         echo "Executing 'docker compose --file $COMPOSE_FILE --profile $profile up -d'..."
+         docker compose --file $COMPOSE_FILE --profile $profile up -d
+         echo "Docker Compose $profile services have been started."
+         echo ""
+         show_docker_compose_status
+         echo ""
+      else
+         echo "Docker Compose $profile services already running...."
+         fi
+    else
+       echo "Invalid argument. Usage: appliance start [redhat|suse]"
+       exit 1
     fi
+
 }
 
 stop_docker_compose() {
-    if [ "$1" = "redhat" ] || [ "$1" = "suse" ]; then
-           echo "Stopping $1 Docker Compose services..."
-           docker compose --file /home/hpe/docker-sap-hana-deploy/ansible/compose.yml --profile $1 down
-	   echo ""
-           echo "Docker Compose $1 services have been stopped..."
-	   sudo systemctl stop nfs-kernel-server
-           echo "nfs-kernel-server service has been stopped..."
-    else
-        echo "Invalid argument. Usage: appliance stop [redhat|suse]"
-    fi
+    profile=$1
+
+    if [ "$profile" = "redhat" ] || [ "$profile" = "suse" ]; then
+         #Check Docker Compose Service
+         container_ids=$(docker compose --file "$COMPOSE_FILE" ps --services "$profile-ansible" -q )  
+
+         if [ "$container_ids" ]; then
+            read -p "Are you sure you want to stop Docker Compose services for $profile? (y/n) " choice
+	    case "$choice" in
+                y|Y )
+                   echo "Stopping $1 Docker Compose services..."
+	           docker compose --file $COMPOSE_FILE --profile $profile down
+                   echo ""
+                   echo "Docker Compose $profile services have been stopped..."
+                   if is_service_running nfs-kernel-server; then
+                    sudo systemctl stop nfs-kernel-server
+                    echo "nfs-kernel-server service has been stopped..."
+	           fi
+               ;;
+               n|N )
+                 echo "Stop operation cancelled."
+                 return  # Exit the function
+               ;;
+               * )
+                 echo "Invalid input"
+               ;;
+            esac
+	 else
+             echo "Docker Compose $profile services not running...."
+           fi   
+       else
+           echo "Invalid argument. Usage: appliance stop [redhat|suse]"
+	   exit 1
+       fi
 }
 
 connect_docker_compose() {
-    if [ "$1" = "redhat" ] || [ "$1" = "suse" ]; then
-        case "$1" in
-            "redhat")
-                echo "Connecting Redhat Docker Compose services..."
-                docker exec -it ansible-rhel /bin/bash
-                ;;
-            "suse")
-                echo "Connecting Suse Docker Compose services..."
-                docker exec -it ansible-sles /bin/bash
-                ;;
-        esac
+    profile=$1
+
+    if [ "$profile" = "redhat" ] || [ "$profile" = "suse" ]; then
+	#Check Docker Compose Service
+        container_ids=$(docker compose --file "$COMPOSE_FILE" ps --services "$profile-ansible" -q )
+
+        if [ "$container_ids" ]; then
+           case "$profile" in
+               "redhat")
+                   echo "Connecting Redhat Docker Compose services..."
+                   docker exec -it ansible-rhel /bin/bash
+                   ;;
+               "suse")
+                   echo "Connecting Suse Docker Compose services..."
+                   docker exec -it ansible-sles /bin/bash
+                   ;;
+           esac
+        else
+             echo "Docker Compose $profile services not running...."
+           fi
     else
         echo "Invalid argument. Usage: appliance connect [redhat|suse]"
+	exit 1
     fi
 }
 
 # Function to show Docker Compose status
 show_docker_compose_status() {
     echo "Docker Compose Service Status..."
-    docker compose --file /home/hpe/docker-sap-hana-deploy/ansible/compose.yml ps
+    #docker compose --file $COMPOSE_FILE ps --all
+    docker compose --file $COMPOSE_FILE ps --format "table {{.Name}}\t{{.Service}}\t{{.CreatedAt}}\t{{.Status}}\t{{.Ports}}"
+}
+
+# Helper function for cleaner service checks
+is_service_running() {
+    [[ $(sudo systemctl is-active $1) == "active" ]]
+}
+
+ensure_service_running() {
+    if ! is_service_running "$1"; then
+        echo "Starting $1..."
+        sudo systemctl start "$1" 
+        if ! is_service_running "$1"; then
+            echo "Failed to start $1. Exiting."
+            exit 1
+        fi
+    fi
+}
+
+cleanup_on_exit() {
+  echo "Script terminated. Performing cleanup..."
+  docker-compose --file "$COMPOSE_FILE" --profile $profile down
+  if is_service_running "nfs-kernel-server"; then
+     sudo systemctl stop nfs-kernel-server
+  fi
 }
 
 display_help() {
@@ -82,11 +138,12 @@ display_help() {
     echo "    suse    Start/Stop Docker Suse Compose services."
 }
 
+trap cleanup_on_exit SIGINT SIGTERM
+
 # Check if a specific function is provided as a command line argument
 if [ $# -eq 2 ]; then
     ACTION=$1
     PROFILE=$2
-
     case "$ACTION" in
         "start")
             start_docker_compose $PROFILE
@@ -105,7 +162,6 @@ if [ $# -eq 2 ]; then
     esac
 elif [ $# -eq 1 ]; then
     ACTION=$1
-
     case "$ACTION" in
         "status")
             show_docker_compose_status
@@ -119,6 +175,9 @@ elif [ $# -eq 1 ]; then
             display_help
             ;;
     esac
+elif [ $# -eq 0 ]; then
+    echo "Missing arguments."
+    display_help
 else
     echo "Invalid action..."
     echo ""
